#!/bin/bash

if [ "$#" -lt 1 ]
then
  echo ""
  echo "Git add, commit and push Kang's config"
  echo ""
  echo "Usage:    $0 <commit>"
  echo "<commit>: (input) the commit content, should be surroounded by \" \" "
  echo ""
  exit -1;
fi

git add .
git commit -m "$1"
git push
