#####################################################
# zshrc
# Used for environment variable configuration.
# Kang Liang 2020/11/26
#####################################################

# Enable colors and change prompt:
setopt interactive_comments

# Basic auto/tab complete:
zstyle ':completion:*' menu select
zmodload zsh/complist

# vi mode
bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# Change cursor shape for different vi modes.
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;      # block
        viins|main) echo -ne '\e[5 q';; # beam
    esac
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q' # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.

source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh 2>/dev/null
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=250'
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# trelis
alias settrelis='nohup /opt/Trelis-16.5/bin/rlm &'

## better command
alias rm='rmtrash'
alias rmdir='rmdirtrash'
alias sudo='sudo '

alias cat='ccat'

alias ls='exa'

alias find='fd'

alias grep='rg'

alias clc='clear'

alias P='~/linux_scripts/sshPacific.sh'
alias R='~/linux_scripts/sshRadarvm.sh'
# set vim as default editor
export VISUAL=nvim;
export EDITOR=nvim;

eval $(thefuck --alias)
# fzf
export FZF_DEFAULT_COMMAND='fd';
export FZF_COMPLETION_TRIGGER='\';
export fzf_preview_cmd='[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500';
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

# alias
alias v="nvim"
#alias vi="nvim"
alias vim="nvim"
export QT_QPA_PLATFORMTHEME=qt5ct;

source ~/.config/zsh/all.sh
